version: "3"

services:
  namenode:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: namenode
    environment:
      - CLUSTER_NAME=test-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9870:9870" # Interface web du NameNode
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    networks:
      - hadoop-spark

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - SERVICE_PRECONDITION=namenode:8020
    ports:
      - "9864:9864" # Interface web DataNode 1
    networks:
      - hadoop-spark

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - SERVICE_PRECONDITION=namenode:8020
    ports:
      - "9865:9864" # Interface web DataNode 2
    networks:
      - hadoop-spark

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - SERVICE_PRECONDITION=namenode:8020
    ports:
      - "9866:9864" # Interface web DataNode 3
    networks:
      - hadoop-spark

  spark-master:
    image: spark:3.5.3-scala2.12-java17-python3-ubuntu
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_UI_PORT=8080
    ports:
      - "8080:8080" # Interface Web Spark Master
      - "7077:7077" # Port d'écoute pour les Workers
    volumes:
      - ./data:/data # Volume partagé pour les fichiers CSV et Parquet
    networks:
      - hadoop-spark

  spark-worker-1:
    image: spark:3.5.3-scala2.12-java17-python3-ubuntu
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    depends_on:
      - spark-master
    networks:
      - hadoop-spark
    ports:
      - "8081:8081" # Interface Premier worker

  spark-worker-2:
    image: spark:3.5.3-scala2.12-java17-python3-ubuntu
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    depends_on:
      - spark-master
    networks:
      - hadoop-spark
    ports:
      - "8082:8081" # Interface Deuxième worker

  jupyter:
    image: jupyter/pyspark-notebook:spark-3.5.0
    container_name: jupyter
    ports:
      - "8888:8888" # Interface Web Jupyter Notebook
    volumes:
      - ./data:/home/jovyan/data # Accès aux fichiers depuis Jupyter
    networks:
      - hadoop-spark
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS=notebook

networks:
  hadoop-spark:
    driver: bridge
